language: python
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.6
      env: TOX_ENV=flake8
install:
- pip install -U tox
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDE0YzU1YjU2LWMxOWItNGMyNi05ZDkwLWVlYTc3MzZmZmM5NwACP3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJzd2FnZ2VyLXBhcnNlciJdfSwgInZlcnNpb24iOiAxfQAABiCBt51FKTKc5aKkDo7oXxBtFvbQxy_iDvSrlqUzcZk5cg"
  on:
    tags: true
    branch: master
    repo: cyprieng/swagger-parser
    condition: $TOX_ENV == py36
